"""POST /export-onboarding — generate ONBOARDING.md from analysis session."""

from __future__ import annotations

from datetime import datetime
from fastapi import APIRouter, HTTPException

from src.api.models import ExportRequest, ExportResponse
from src.api import session_store
from src.diagrams.mermaid_renderer import MermaidRenderer

router = APIRouter()
_renderer = MermaidRenderer()


@router.post("/export-onboarding", response_model=ExportResponse)
def export_onboarding(req: ExportRequest) -> ExportResponse:
    session = session_store.get(req.analysis_id)
    if not session:
        raise HTTPException(status_code=404, detail="analysis_id not found")

    index      = session["index"]
    call_graph = session["call_graph"]
    dep_graph  = session["dep_graph"]
    source     = session.get("source", "unknown")

    # Symbol stats
    from src.analysis.symbol_index import SymbolKind
    kinds = {k: 0 for k in SymbolKind}
    for sym in index.all_symbols():
        kinds[sym.kind] += 1

    # Top 10 most-called symbols
    top_called = sorted(
        call_graph.all_nodes(),
        key=lambda n: len(n.called_by),
        reverse=True,
    )[:10]

    dep_mermaid  = _renderer.render_dep_graph(dep_graph, title="Module Dependencies")
    call_mermaid = _renderer.render_call_graph(call_graph, title="Call Graph")

    lines = [
        f"# ONBOARDING.md",
        f"",
        f"> Auto-generated by RepoPilot on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"> Source: `{source}`",
        f"",
        f"## Repository Summary",
        f"",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Modules | {kinds[SymbolKind.MODULE]} |",
        f"| Classes | {kinds[SymbolKind.CLASS]} |",
        f"| Methods | {kinds[SymbolKind.METHOD]} |",
        f"| Functions | {kinds[SymbolKind.FUNCTION]} |",
        f"| Total Symbols | {len(index)} |",
        f"",
        f"## Module Dependency Graph",
        f"",
        dep_mermaid,
        f"",
        f"## Call Graph",
        f"",
        call_mermaid,
        f"",
        f"## Most-Called Symbols",
        f"",
    ]

    for node in top_called:
        if node.called_by:
            sym = index.lookup(node.fqn)
            doc = (sym.docstring or "").split("\n")[0][:80] if sym else ""
            lines.append(f"- **`{node.fqn}`** — {len(node.called_by)} callers. {doc}")

    lines += [
        f"",
        f"## Key Modules",
        f"",
    ]

    for mod in sorted(index.all_modules(), key=lambda s: s.fqn):
        syms = index.symbols_in_module(mod.module_fqn)
        classes = [s for s in syms if s.kind == SymbolKind.CLASS]
        fns     = [s for s in syms if s.kind == SymbolKind.FUNCTION]
        lines.append(f"### `{mod.fqn}`")
        lines.append(f"- File: `{mod.file_path}`")
        if classes:
            lines.append(f"- Classes: {', '.join(f'`{c.name}`' for c in classes)}")
        if fns:
            lines.append(f"- Functions: {', '.join(f'`{f.name}`' for f in fns[:8])}")
        lines.append("")

    markdown = "\n".join(lines)

    return ExportResponse(
        analysis_id = req.analysis_id,
        markdown    = markdown,
        filename    = "ONBOARDING.md",
    )
